config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get "homes/about" => "homes#about"
  devise_for :users
  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users do
    member do
      put 'hide'
    end
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(params[:user_id])
    current_user.follow(params[:user_id])
  end

  def destroy
    @user = User.find(params[:user_id])
    current_user.unfollow(params[:user_id])
  end

  def followings
    @users = user.followings
    @user = User.find(params[:user_id])
  end

  def followers
    @users = user.followers
    @user = User.find(params[:user_id])
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_index.html.erb
<table class='table table-striped'>
  <thead>
    <tr>
      <th></th>
      <th>name</th>
      <th>follow</th>
      <th>follower</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, size: "50x50", fallback: "no_image.jpg" %></td>
        <td><%= user.name %></td>
        <td><%= user.followings.count %></td>
        <td><%= user.followers.count %></td>
        <td><%= link_to "Show", user_path(user), class: "btn btn-secondary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/relationships/_relationship.html.erb
 <% if current_user.following?(user) %>
  <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, remote: true, class: "btn btn-danger" %>
 <% else %>
  <%= link_to "フォローする", user_relationships_path(user.id), method: :post, remote: true, class: "btn btn-success" %>
 <% end %>

app/views/relationships/create.js.erb
$('#follow_buttons_<%= @user.id %>').html("<%= j(render "relationships/relationship", user: @user) %>");
$('#following-count_<%= @user.id %>').html("<%= j(link_to "#{ @user.followings.count }", user_followings_path(@user)) %>");
$('#follower-count_<%= @user.id %>').html("<%= j(link_to "#{ @user.followers.count }", user_followings_path(@user)) %>");

app/views/relationships/destroy.js.erb
$('#follow_buttons_<%= @user.id %>').html("<%= j(render "relationships/relationship", user: @user) %>");
$('#following-count_<%= @user.id %>').html("<%= j(link_to "#{ @user.followings.count }", user_followings_path(@user)) %>");
$('#follower-count_<%= @user.id %>').html("<%= j(link_to "#{ @user.followers.count }", user_followings_path(@user)) %>");

app/views/relationships/followers.html.erb
<div class="container">
  <div class="row">

    <div class="col-lg-7 col-md-8 mx-auto">
      <h2><%= @user.name %>'s Followers</h2>
      <% if @users.exists? %>
        <%= render 'index', users: @users %>
      <% else %>
        <p>ユーザーはいません</p>
      <% end %>
    </div>
  </div>
</div>

app/views/relationships/followings.html.erb
<div class="container">
  <div class="row">

    <div class="col-lg-7 col-md-8 mx-auto">
      <h2><%= @user.name %>'s Follows</h2>
      <% if @users.exists? %>
        <%= render 'index', users: @users %>
      <% else %>
        <p>ユーザーはいません</p>
      <% end %>
    </div>
  </div>
</div>