config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get "homes/about" => "homes#about"
  devise_for :users
  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users do
    member do
      put 'hide'
    end
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :validatable

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 10 }
  validates :intro, length: { maximum: 50 }

  has_many :post, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  attachment :profile_image

  def active_for_authentication?
    super && (self.is_valid == true)
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @posts = @user.post.page(params[:page]).per(5)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
      flash[:notice] = "更新しました"
    else
      render :edit
    end
  end

  def hide
    @user = User.find(params[:id])
    @user.update(is_valid: false)
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :intro)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(posts_path) unless @user == current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-8 px-5 mx-auto">
        <div class="form-group">
          <%= form_with model: @user, local: true do |f| %>
           <label>Name</label>
           <%= f.text_field :name, class: "form-control" %>
           <label>Image</label>
           <%= f.attachment_field :profile_image, class: "form-control-file" %>
           <label>Intro</label>
           <%= f.text_area :intro, class: "form-control" %>
           <%= f.submit class: "btn" %>
          <% end %>
        </div>
      </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, class: "mt-1 rounded-circle", size: "100x100", fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr>
            <td>name</td>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <td>intro</td>
            <td><%= @user.intro %></td>
          </tr>
          <tr>
            <td>follow</td>
            <td id="following-count_<%= @user.id %>">
              <%= link_to "#{ @user.followings.count }", user_followings_path(@user) %>
            </td>
          </tr>
          <tr>
            <td>follower</td>
            <td id=follower-count_<%= @user.id %>>
              <%= link_to "#{ @user.followers.count }", user_followings_path(@user) %>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="d-grid gap-1">
        <% if user_signed_in? && @user.id == current_user.id %>
          <%= link_to edit_user_path(@user) do %>
           <button type="button" class="btn btn-success">Edit</button>
          <% end %>
          <%= link_to "退会", hide_user_path(@user), method: :put, "data-confirm" => "本当に退会しますか？", class: "btn btn-danger" %>
        <% else %>
          <div id="follow_buttons_<%= @user.id %>">
           <%= render "relationships/relationship", user: @user %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-7 mt-auto">
      <% @posts.each do |post| %>
       <div class="card w-80 mx-auto mt-1">
         <%= link_to post_path(post.id) do %>
           <%= attachment_image_tag post, :picture, class:"card-img-top" %>
         <% end %>
         <div class="card-body">
           <div class="row">
             <div class="col-10">
               <h3 class="card-title">
                 <%= post.title %>
               </h3>
             </div>
           </div>
         </div>
       </div>
      <% end %>
      <%= paginate @posts %>
    </div>
  </div>
</div>