config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get "homes/about" => "homes#about"
  devise_for :users
  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users do
    member do
      put 'hide'
    end
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  attachment :picture
  has_many :post_comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true
  validates :picture, presence: true
  validates :cook, presence: true

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = "投稿が完了しました"
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def index
    @posts = Post.page(params[:page]).per(5)
    @post_like_ranks = Post.find(Like.group(:post_id).order('count(post_id) desc').limit(5).pluck(:post_id))
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "変更しました"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def search #検索機能
    if params[:keyword].present?
      @posts = Post.where('title LIKE ?', "%#{params[:keyword]}%").page(params[:page]).per(9) #:keywordが:titleに含まれているものを表示
      @keyword = params[:keyword]
    else
      @posts = Post.page(params[:page]).per(9) #空白で検索した場合
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :picture, :cook)
  end

  def correct_user
    @post = Post.find(params[:id])
    redirect_to(posts_path) unless @user == current_user
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post_comments.html.erb
<table class="table">
   <% post.post_comments.each do |post_comment| %>
     <tr>
       <td>
         <%= attachment_image_tag post_comment.user, :profile_image, class: "mt-1 rounded-circle", size: "30x30", fallback: "no_image.jpg" %>
         <%= post_comment.user.name %>
         <%= post_comment.created_at.strftime('%Y/%m/%d') %>
       </td>
       <td class= "text-center"><%= post_comment.comment %></td>
       <td>
         <% if current_user == post_comment.user %>
           <%= link_to "delete", post_post_comment_path(post_comment.post, post_comment), method: :delete %>
         <% end %>
        </td>
     </tr>
   <% end %>
</table>

  <%= form_with(model:[post, @post_comment], local: true) do |f| %>
   <%= f.text_area :comment, class: "form-control",placeholder: "コメントをここに" %>
   <%= f.submit "送信", class: "btn m-1" %>
  <% end %>

app/views/posts/_window.html.erb
<div class="window">
  <%= form_with url: search_posts_path, local: true, method: :get do |f| %>
   <%= f.text_field :keyword, class: "input" %>
   <button class="fas fa-search"></button>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
     <div class="col-md-8 px-5 px-sm-0 mx-auto">
       <%= render 'layouts/error', obj: @post %>
       <h2>edit</h2>
       <div class="form-group">
         <%= form_with model: @post, local: true do |f| %>
         <label>Title</label>
          <%= f.text_field :title, class: "form-control" %>
         <label>Image</label>
         <%= f.attachment_field :picture, class: "form-control-file" %>
         <label>Recipe</label>
         <%= f.text_area :cook, size: "80x20", class: "form-control" %>
         <%= f.submit 'Save', class: "btn" %>
       </div>
       <% end %>
     </div>
   </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-7 col-md-7 mx-auto">
      <div class="mx-auto mt-1">
        <h2>投稿一覧</h2>
        <% @posts.each do |post| %>
          <div class="card">
            <%= link_to post_path(post.id) do %>
             <%= attachment_image_tag post, :picture, class:"card-img-top" %>
            <% end %>
            <div class="card-body">
              <div class="row">
                <div class="col-2">
                  <%= link_to post.user do %>
                   <%= attachment_image_tag post.user, :profile_image, class: "mt-1 rounded-circle", size: "50x50", fallback: "no_image.jpg" %>
                  <% end %>
                </div>
                <div class="col-7">
                  <h4 class="card-title">
                    <strong><%= post.title %></strong>
                  </h4>
                </div>
                <div class="col-1">
                  <i class="far fa-comment-dots"><%= post.post_comments.count %></i>
                </div>
                <div class="col-1 mx-1">
                  <i class="far fa-heart"><%= post.likes.count %></i>
                </div>
              </div>
            </div>
          </div>
        <% end %>
        <%= paginate @posts %>
      </div>
    </div>
    <div class="col-lg-3 col-md-3 mx-auto">
      <div class="mx-auto mt-1">
        <h4 class="fas fa-crown">いいね数ランキング</h4>
        <% last_like = 0 %>
        <% j = 1 %>
        <% @post_like_ranks.each.with_index(1) do |post, i| %>
          <% if i == 1 %>
           <% last_like = post.likes.count %>
          <% end %>
          <% if post.likes.count != last_like %>
           <% j = i %>
           第<%= j %>位
           <%= link_to post_path(post.id) do %>
             <%= attachment_image_tag post, :picture, class: "rank-picture" %>
           <% end %>
           <% last_like = post.likes.count %>
         <% else %>
           <% last_like = post.likes.count %>
            第<%= j %>位
           <%= link_to post_path(post.id) do %>
             <%= attachment_image_tag post, :picture, class: "rank-picture" %>
           <% end %>
         <% end %>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
   <div class="row">
      <div class=" col-md-8 px-5 px-sm-0 mx-auto">
         <%= render 'layouts/error', obj: @post %>
         <h3>New recipe</h3>
         <div class="form-group">
          <%= form_with model: @post, local:true do |f| %>
               <label>Title</label>
               <%= f.text_field :title, class: "form-control" %>
               <label>Image</label>
               <%= f.attachment_field :picture, class: "form-control-file" %>
               <label>Recipe</label>
               <%= f.text_area :cook, size: "80x20", class: "form-control" %>
               <%= f.submit "Post", class: "btn" %>
          <% end %>
         </div>
      </div>
   </div>
</div>

app/views/posts/search.html.erb
<div class="container">
  <div class="row">
    <h2>Search for..."<%= @keyword %>"</h2>
    <div class="w-75 mx-auto mt-2 py-5 ">
      <% @posts.each do |post| %>
        <%= link_to post_path(post.id) do %>
          <%= attachment_image_tag post, :picture, class: "mt-3 mx-1 search-thumb-image" %>
        <% end %>
      <% end %>
      <%= paginate @posts %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 px-5 px-sm-0 mx-auto">
      <div class="mx-auto mt-1">
        <h2>
          <strong><%= @post.title %></strong>
          <strong  id="like_buttons_<%= @post.id %>"><%= render "likes/like", post: @post %></strong>
        </h2>
        <%= attachment_image_tag @post, :picture, class: "text-center", height: "50%", width: "100%" %>
        <p class="select">
         <%= link_to 'back', posts_path, class: "btn m-1" %>
          <% if @post.user == current_user %>
           <%= link_to 'edit', edit_post_path(@post), class: "btn m-1" %>
           <%= link_to 'delete', post_path(@post), method: :delete, class: "btn m-1" %>
          <% end %>
        </p>
        <p><%= safe_join(@post.cook.split("\n"),tag(:br)) %></p>
        <p><%= @post.user.name %></p>
        <p>コメント件数：<%= @post.post_comments.count %></p>
        <%= render 'post_comments', post: @post %>
      </div>
    </div>
  </div>
</div>